import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=()=>readFile(new URL('../app/public/bond-ui.js',import.meta.url),'utf8');
test('dedications exclude unopened capsules and never copy their body',async()=>{const {dedicationOptions}=await import('../app/public/bond-ui.js');const html=dedicationOptions([{id:'secret',kind:'capsule',data:{title:'Hidden',body:'PRIVATE',openDate:'2099-01-01'}},{id:'m',kind:'memory',data:{title:'Our day',body:'PRIVATE'}}],'2026-10-02');assert.ok(!html.includes('secret'));assert.ok(!html.includes('PRIVATE'));assert.ok(html.includes('Our day'));});
test('independent moments transport deduplicates and discards a changed session',async()=>{const {createBondLoader}=await import('../app/public/bond-ui.js');let resolve,person='0',calls=0;const loader=createBondLoader(()=>{calls++;return new Promise(r=>resolve=r)},()=>person);const a=loader.load(),b=loader.load();assert.equal(calls,1);person='1';resolve({entries:['private']});assert.equal(await a,null);assert.equal(await b,null);});
test('recordings release tracks and enforce recording limits',async()=>{const s=await source();assert.match(s,/60_000/);assert.match(s,/5\s*\*\s*1024\s*\*\s*1024/);assert.match(s,/getTracks\(\).*stop\(/s);assert.match(s,/X-File-Name/);assert.match(s,/URL.revokeObjectURL/);});
test('Pages ships moments modules and accessible styles',async()=>{const s=await readFile(new URL('../scripts/build-pages.mjs',import.meta.url),'utf8');for(const name of ['bond-ui.js','bond-domain.js','bond.css'])assert.ok(s.includes(name));const css=await readFile(new URL('../app/public/bond.css',import.meta.url),'utf8');assert.ok(css.includes('prefers-reduced-motion'));assert.ok(css.includes('minmax(0,1fr)'));});

test('moments requests time out and can retry without blocking navigation',async()=>{const {createBondLoader}=await import('../app/public/bond-ui.js');let calls=0;const loader=createBondLoader(()=>++calls===1?new Promise(()=>{}):Promise.resolve({entries:[]}),()=> '0',10);await assert.rejects(loader.load(),/tardando/);assert.deepEqual(await loader.load(),{entries:[]});});

test('partner game hides answer before guess and reveals friendly result afterwards',async()=>{const {gameMarkup}=await import('../app/public/bond-ui.js');const state={person:'1',settings:{data:{names:['Juan','Adriana']}}};const game={id:'g',author:'0',data:{questionId:'comfort',answer:'PRIVATE ANSWER'}};const hidden=gameMarkup(game,state);assert.ok(!hidden.includes('PRIVATE ANSWER'));assert.ok(hidden.includes('data-bond-form="guess"'));const revealed=gameMarkup({...game,data:{...game.data,guess:'Un abrazo',correct:false}},state);assert.ok(revealed.includes('PRIVATE ANSWER'));assert.ok(revealed.includes('seguir conversando'));assert.ok(!revealed.includes('data-bond-form="guess"'));});

test('explicit note recovery saves preserved draft against newest version',async()=>{const {saveSharedDraft}=await import('../app/public/bond-ui.js');let note={id:'n',version:4,data:{title:'Partner',body:'new text'}};const draft={title:'Mine',body:'unfinished words'};const api=async(url,options)=>{if(!options)return {entries:[structuredClone(note)]};const payload=JSON.parse(options.body);if(payload.version!==note.version)throw Error('Cambió en otro dispositivo.');note={...note,version:note.version+1,data:payload.data};return note;};await saveSharedDraft(api,'n',draft,4);assert.equal(note.version,5);assert.deepEqual(note.data,draft);assert.deepEqual(draft,{title:'Mine',body:'unfinished words'});});
test('another writer during conflict recovery preserves draft and exposes newest comparison',async()=>{const {saveSharedDraft,conflictMarkup}=await import('../app/public/bond-ui.js');let note={id:'n',version:2,data:{title:'First',body:'text'}};const draft=Object.freeze({title:'Draft',body:'keep this'});const api=async(url,options)=>{if(!options)return {entries:[structuredClone(note)]};note={...note,version:3,data:{title:'Latest',body:'Other edit <script>'}};throw Error('Cambió en otro dispositivo.');};let failure;try{await saveSharedDraft(api,'n',draft,2);}catch(e){failure=e;}assert.deepEqual(failure.latest,note);assert.equal(draft.body,'keep this');const html=conflictMarkup(failure.latest);assert.ok(html.includes('Cargar versión nueva'));assert.ok(html.includes('Guardar mi borrador sobre la versión nueva'));assert.ok(html.includes('Other edit &lt;script&gt;'));});

test('overwrite only applies to the version actually compared, preserving an unseen newer edit',async()=>{const {saveSharedDraft}=await import('../app/public/bond-ui.js');let note={id:'n',version:3,data:{title:'Unseen newer edit',body:'partner v3'}};const draft=Object.freeze({title:'Draft',body:'my unsaved words'});const api=async(url,options)=>{if(!options)return {entries:[structuredClone(note)]};const payload=JSON.parse(options.body);if(payload.version!==note.version)throw Error('Cambió en otro dispositivo.');note={...note,version:4,data:payload.data};return note;};let failure;try{await saveSharedDraft(api,'n',draft,2);}catch(e){failure=e;}assert.ok(failure);assert.equal(note.version,3);assert.equal(note.data.body,'partner v3');assert.equal(failure.latest.version,3);assert.equal(draft.body,'my unsaved words');});

test('a dedication opens only its referenced available memory and never exposes a closed capsule',async()=>{
 const {dedicationLink}=await import('../app/public/bond-ui.js');
 const items=[{id:'m',kind:'memory',data:{title:'Nuestro paseo',body:'private'}},{id:'c',kind:'capsule',data:{title:'Futuro',unlockDate:'2099-01-01',body:'secret'}}];
 assert.match(dedicationLink('m',items,'2026-10-02'),/data-action="detail" data-id="m"/);
 assert.match(dedicationLink('m',items,'2026-10-02'),/Nuestro paseo/);
 assert.equal(dedicationLink('c',items,'2026-10-02'),'');assert.equal(dedicationLink('unknown',items,'2026-10-02'),'');
});
