package com.nuestragalaxia.companion;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.Build;import android.provider.Settings;import androidx.core.content.FileProvider;import org.json.JSONObject;import java.io.*;import java.net.*;import java.security.MessageDigest;import java.util.Locale;import java.util.concurrent.*;
public final class UpdateManager {
 public interface Listener{void onState(String text,int progress,boolean busy);} private static final String MANIFEST_URL="https://github.com/Berserky/Galaxia-de-girasoles/releases/download/android-stable/update.json"; private final Activity activity;private final Listener listener;private final ExecutorService io=Executors.newSingleThreadExecutor();
 public UpdateManager(Activity a,Listener l){activity=a;listener=l;} public void check(boolean manual){emit("Buscando actualización…",0,true);io.execute(()->{try{JSONObject m=new JSONObject(readText(MANIFEST_URL));if(m.getInt("versionCode")<=BuildConfig.VERSION_CODE){emit(manual?"Ya tienes la versión más reciente.":"",100,false);return;}String v=m.getString("versionName"),u=m.getString("apkUrl"),s=m.getString("sha256");activity.runOnUiThread(()->new AlertDialog.Builder(activity).setTitle("Actualización "+v).setMessage(m.optString("notes","Hay una nueva versión disponible.")).setNegativeButton("Más tarde",(d,w)->emit("Actualización pendiente.",0,false)).setPositiveButton("Actualizar",(d,w)->download(u,s)).show());}catch(Exception e){emit("No se pudo comprobar la actualización: "+safe(e),0,false);}});}
 private void download(String url,String sha){io.execute(()->{File out=new File(activity.getCacheDir(),"updates/NuestraGalaxia-update.apk");try{File dir=out.getParentFile();if(dir!=null&&!dir.exists())dir.mkdirs();HttpURLConnection c=open(url);int total=c.getContentLength(),done=0;byte[] b=new byte[65536];try(InputStream in=c.getInputStream();OutputStream os=new FileOutputStream(out)){int n;while((n=in.read(b))>0){os.write(b,0,n);done+=n;if(total>0)emit("Descargando actualización…",Math.min(99,done*100/total),true);}}emit("Verificando paquete…",99,true);if(!sha256(out).equalsIgnoreCase(sha))throw new SecurityException("La verificación SHA-256 no coincide");emit("Preparando instalación…",100,true);activity.runOnUiThread(()->install(out));}catch(Exception e){if(out.exists())out.delete();emit("Error de actualización: "+safe(e),0,false);}});}
 private void install(File apk){if(Build.VERSION.SDK_INT>=26&&!activity.getPackageManager().canRequestPackageInstalls()){emit("Autoriza a Nuestra Galaxia para instalar su actualización.",100,false);activity.startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+activity.getPackageName())));return;}Uri uri=FileProvider.getUriForFile(activity,activity.getPackageName()+".files",apk);activity.startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK));emit("Android está listo para instalar la actualización.",100,false);}
 private static HttpURLConnection open(String raw)throws Exception{URL u=new URL(raw);for(int r=0;r<6;r++){HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setInstanceFollowRedirects(false);c.setRequestProperty("User-Agent","NuestraGalaxia-Android/"+BuildConfig.VERSION_NAME);int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");c.disconnect();if(loc==null)throw new IOException("Redirección inválida");u=new URL(u,loc);continue;}if(code<200||code>=300)throw new IOException("HTTP "+code);return c;}throw new IOException("Demasiadas redirecciones");}
 private static String readText(String url)throws Exception{HttpURLConnection c=open(url);try(InputStream in=c.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);return o.toString("UTF-8");}finally{c.disconnect();}}
 private static String sha256(File f)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[] b=new byte[65536];int n;while((n=in.read(b))>0)md.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte b:md.digest())s.append(String.format(Locale.US,"%02x",b));return s.toString();}
 private void emit(String t,int p,boolean b){activity.runOnUiThread(()->listener.onState(t,p,b));}private static String safe(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}public void close(){io.shutdownNow();}
}