alter table public.galaxy_locations
 add column if not exists status text,
 add column if not exists trip_active boolean not null default false,
 add column if not exists trip_started_at timestamptz;

create table if not exists public.galaxy_places (
 id bigint generated by default as identity primary key,
 owner text not null check (owner in ('0','1')),
 kind text not null check (kind in ('home','work','memory','adventure')),
 name text not null check (char_length(name) between 1 and 80),
 latitude double precision not null check (latitude between -90 and 90),
 longitude double precision not null check (longitude between -180 and 180),
 note text,
 created_at timestamptz not null default now()
);
alter table public.galaxy_places enable row level security;
drop policy if exists places_read on public.galaxy_places;
create policy places_read on public.galaxy_places for select to authenticated using (public.galaxy_person() is not null);
drop policy if exists places_insert_own on public.galaxy_places;
create policy places_insert_own on public.galaxy_places for insert to authenticated with check (owner=public.galaxy_person());
drop policy if exists places_update_own on public.galaxy_places;
create policy places_update_own on public.galaxy_places for update to authenticated using (owner=public.galaxy_person()) with check (owner=public.galaxy_person());
drop policy if exists places_delete_own on public.galaxy_places;
create policy places_delete_own on public.galaxy_places for delete to authenticated using (owner=public.galaxy_person());
grant select,insert,update,delete on public.galaxy_places to authenticated;
grant usage,select on sequence public.galaxy_places_id_seq to authenticated;

create table if not exists public.galaxy_trip_points (
 id bigint generated by default as identity primary key,
 person text not null check (person in ('0','1')),
 latitude double precision not null check (latitude between -90 and 90),
 longitude double precision not null check (longitude between -180 and 180),
 created_at timestamptz not null default now()
);
alter table public.galaxy_trip_points enable row level security;
drop policy if exists trip_points_read on public.galaxy_trip_points;
create policy trip_points_read on public.galaxy_trip_points for select to authenticated using (public.galaxy_person() is not null);
drop policy if exists trip_points_insert_own on public.galaxy_trip_points;
create policy trip_points_insert_own on public.galaxy_trip_points for insert to authenticated with check (person=public.galaxy_person());
drop policy if exists trip_points_delete_own on public.galaxy_trip_points;
create policy trip_points_delete_own on public.galaxy_trip_points for delete to authenticated using (person=public.galaxy_person());
grant select,insert,delete on public.galaxy_trip_points to authenticated;
grant usage,select on sequence public.galaxy_trip_points_id_seq to authenticated;
do $$ begin
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='galaxy_places') then alter publication supabase_realtime add table public.galaxy_places; end if;
end $$;