alter table public.galaxy_items drop constraint if exists galaxy_items_kind_check;
alter table public.galaxy_items add constraint galaxy_items_kind_check check(kind in ('memory','song','event','plan','note','capsule','wish','journey'));

create table public.galaxy_destinations (
 person text primary key check(person in ('0','1')),
 kind text not null check(kind in ('person','place')),
 target_person text check(target_person is null or target_person in ('0','1')),
 place_id bigint references public.galaxy_places(id) on delete set null,
 label text not null check(length(label)<=80),
 active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 check((kind='person' and target_person is not null) or (kind='place' and place_id is not null))
);
alter table public.galaxy_destinations enable row level security;
create policy destinations_read on public.galaxy_destinations for select to authenticated using(public.galaxy_person() is not null);
create policy destinations_write_own on public.galaxy_destinations for all to authenticated using(person=public.galaxy_person()) with check(person=public.galaxy_person());
revoke all on public.galaxy_destinations from anon,authenticated;
grant select,insert,update,delete on public.galaxy_destinations to authenticated;

create table public.galaxy_encounters (
 id bigint generated by default as identity primary key,
 started_at timestamptz not null,
 ended_at timestamptz,
 distance_m integer check(distance_m is null or distance_m>=0),
 created_by text not null check(created_by in ('0','1')),
 created_at timestamptz not null default now()
);
create unique index galaxy_encounters_open_idx on public.galaxy_encounters((ended_at is null)) where ended_at is null;
alter table public.galaxy_encounters enable row level security;
create policy encounters_read on public.galaxy_encounters for select to authenticated using(public.galaxy_person() is not null);
create policy encounters_insert on public.galaxy_encounters for insert to authenticated with check(created_by=public.galaxy_person());
create policy encounters_update on public.galaxy_encounters for update to authenticated using(public.galaxy_person() is not null) with check(public.galaxy_person() is not null);
revoke all on public.galaxy_encounters from anon,authenticated;
grant select,insert,update on public.galaxy_encounters to authenticated;
grant usage,select on sequence public.galaxy_encounters_id_seq to authenticated;