create table public.galaxy_place_events (
 id bigint generated by default as identity primary key,
 person text not null check(person in ('0','1')),
 place_id bigint not null references public.galaxy_places(id) on delete cascade,
 event text not null check(event in ('arrived','left')),
 happened_at timestamptz not null default now()
);
create index galaxy_place_events_person_time_idx on public.galaxy_place_events(person,happened_at desc);
alter table public.galaxy_place_events enable row level security;
create policy place_events_read on public.galaxy_place_events for select to authenticated using(public.galaxy_person() is not null);
create policy place_events_insert_own on public.galaxy_place_events for insert to authenticated with check(person=public.galaxy_person());
create policy place_events_delete_own on public.galaxy_place_events for delete to authenticated using(person=public.galaxy_person());
revoke all on public.galaxy_place_events from anon,authenticated;
grant select,insert,delete on public.galaxy_place_events to authenticated;
grant usage,select on sequence public.galaxy_place_events_id_seq to authenticated;