create table public.galaxy_location_history (
 id bigint generated by default as identity primary key,
 person text not null check(person in ('0','1')),
 latitude double precision not null check(latitude between -90 and 90),
 longitude double precision not null check(longitude between -180 and 180),
 accuracy double precision check(accuracy is null or accuracy>=0),
 speed double precision check(speed is null or speed>=0),
 heading double precision check(heading is null or heading between 0 and 360),
 motion text check(motion is null or motion in ('still','walking','vehicle')),
 captured_at timestamptz not null default now()
);
create index galaxy_location_history_person_time_idx on public.galaxy_location_history(person,captured_at desc);
alter table public.galaxy_location_history enable row level security;
create policy location_history_read on public.galaxy_location_history for select to authenticated using(public.galaxy_person() is not null);
create policy location_history_insert_own on public.galaxy_location_history for insert to authenticated with check(person=public.galaxy_person());
create policy location_history_delete_own on public.galaxy_location_history for delete to authenticated using(person=public.galaxy_person());
revoke all on public.galaxy_location_history from anon,authenticated;
grant select,insert,delete on public.galaxy_location_history to authenticated;
grant usage,select on sequence public.galaxy_location_history_id_seq to authenticated;

create table public.galaxy_trip_history (
 id bigint generated by default as identity primary key,
 person text not null check(person in ('0','1')),
 started_at timestamptz not null,
 ended_at timestamptz not null default now(),
 distance_m integer not null default 0 check(distance_m>=0),
 duration_s integer not null default 0 check(duration_s>=0),
 max_speed double precision check(max_speed is null or max_speed>=0),
 dominant_motion text check(dominant_motion is null or dominant_motion in ('still','walking','vehicle')),
 created_at timestamptz not null default now()
);
create index galaxy_trip_history_person_time_idx on public.galaxy_trip_history(person,started_at desc);
alter table public.galaxy_trip_history enable row level security;
create policy trip_history_read on public.galaxy_trip_history for select to authenticated using(public.galaxy_person() is not null);
create policy trip_history_insert_own on public.galaxy_trip_history for insert to authenticated with check(person=public.galaxy_person());
create policy trip_history_delete_own on public.galaxy_trip_history for delete to authenticated using(person=public.galaxy_person());
revoke all on public.galaxy_trip_history from anon,authenticated;
grant select,insert,delete on public.galaxy_trip_history to authenticated;
grant usage,select on sequence public.galaxy_trip_history_id_seq to authenticated;