val firebaseProjectId = providers.gradleProperty("FIREBASE_PROJECT_ID").orNull ?: System.getenv("FIREBASE_PROJECT_ID") ?: ""
val firebaseApplicationId = providers.gradleProperty("FIREBASE_APPLICATION_ID").orNull ?: System.getenv("FIREBASE_APPLICATION_ID") ?: ""
val firebaseApiKey = providers.gradleProperty("FIREBASE_API_KEY").orNull ?: System.getenv("FIREBASE_API_KEY") ?: ""
val firebaseSenderId = providers.gradleProperty("FIREBASE_SENDER_ID").orNull ?: System.getenv("FIREBASE_SENDER_ID") ?: ""

plugins { id("com.android.application") }
android { namespace = "com.nuestragalaxia.companion"; compileSdk = 36
 defaultConfig { applicationId = "com.nuestragalaxia.companion"; minSdk = 26; targetSdk = 36; versionCode = 23; versionName = "3.0.1"; buildConfigField("String","SUPABASE_URL","\"https://zqiknzivfahvvadmxrvt.supabase.co\""); buildConfigField("String","SUPABASE_PUBLISHABLE_KEY","\"sb_publishable_c3SvE2qIJthLwd7IcEYSmA_OU2Ku9rT\""); buildConfigField("String","EDGE_URL","\"https://zqiknzivfahvvadmxrvt.supabase.co/functions/v1/android-companion\""); buildConfigField("String","FIREBASE_PROJECT_ID","\"$firebaseProjectId\""); buildConfigField("String","FIREBASE_APPLICATION_ID","\"$firebaseApplicationId\""); buildConfigField("String","FIREBASE_API_KEY","\"$firebaseApiKey\""); buildConfigField("String","FIREBASE_SENDER_ID","\"$firebaseSenderId\""); testInstrumentationRunner = "android.app.InstrumentationTestRunner" }
 buildFeatures { buildConfig = true }; compileOptions { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 } }
dependencies { implementation("com.google.firebase:firebase-messaging:25.1.3"); implementation("com.google.android.gms:play-services-location:21.4.0"); implementation("androidx.core:core:1.17.0"); implementation("androidx.activity:activity:1.13.0"); implementation("androidx.fragment:fragment:1.9.1"); implementation("androidx.work:work-runtime:2.11.2"); implementation("androidx.webkit:webkit:1.15.0"); testImplementation("junit:junit:4.13.2") }